# Generated by Django 3.2.4 on 2021-08-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=50, null=True, unique=True, verbose_name='İsim')),
                ('salesorder', models.CharField(max_length=50, null=True, unique=True, verbose_name='Satış Sırası')),
                ('cattleid', models.CharField(max_length=50, null=True, unique=True, verbose_name='Hayvan Numarası')),
                ('slaughterorder', models.CharField(max_length=50, null=True, unique=True, verbose_name='Kesim Sırası')),
            ],
        ),
    ]
