# Generated by Django 3.2.4 on 2021-08-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='phonenumber',
            field=models.IntegerField(max_length=100, null=True, unique=True, verbose_name='Telefon Numarası'),
        ),
    ]
